# Generated by Django 5.2 on 2025-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_visibility_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.AddField(
            model_name='postimage',
            name='image_url',
            field=models.CharField(default='default.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
