# Generated by Django 5.2 on 2025-04-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_picture_alter_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plec',
            field=models.CharField(choices=[('male', 'Mężczyzna'), ('female', 'Kobieta')], default='male', max_length=6),
        ),
    ]
